version: "3"
services: 
  db:
    image: mongo:4.0.3
    ports:
      - 27017:27017
    restart: always
  api: 
    image: service-api:1.0.1
    ports:
      - 8080:8080
    restart: always
  ui:
    image: alexteusz/languagelevelsearchengine-service-ui:1.0.0
    ports:
      - 80:3000
    restart: always