version: "3.5"

services: 
  # mongo database
  db:
    image: mongo:4.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    deploy:
      restart_policy:
        condition: any
    volumes:
      - 'mongodb:/data/db'
      - ./init:/docker-entrypoint-initdb.d
    ports:
      # external:internal
      - '2717:27017'
    networks:
      - database

  # scrapy webcrawler for filling the database   
  crawler:
    image: alexteusz/languagelevelsearchengine-service-crawler:latest
    deploy:
      restart_policy:
        condition: any
    networks:
      - database

  # python bottle api
  api: 
    image: alexteusz/languagelevelsearchengine-service-api:latest
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    deploy:
      restart_policy:
        condition: any
      labels:
        traefik.frontend.rule: 'Host:api.elaisa.org'
        traefik.port: '8080'
        traefik.enable: 'true'
        traefik.docker.network: frontend
    networks:
      - frontend
      - database

  # reactjs web application user interface
  ui:
    image: alexteusz/languagelevelsearchengine-service-ui:latest
    deploy:
      restart_policy:
        condition: any
      labels:
        traefik.frontend.rule: 'Host:elaisa.org,www.elaisa.org'
        traefik.enable: 'true'
        traefik.port: '80'
        traefik.docker.network: frontend
    networks:
      - frontend

  # reverse proxy
  traefik:
      image: 'traefik:1.7.9-alpine'
      command:
        - --api 
        - --docker 
        - --docker.swarmmode 
        - --docker.watch 
        - --metrics.prometheus
        - --debug=false
        - --logLevel=ERROR
        - --entryPoints=Name:http Address::80
        - --defaultentrypoints=http
        - --defaultentrypoints=https,http
        - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
        - --entryPoints=Name:https Address::443 TLS
        - --retry
        - --docker.endpoint=unix:///var/run/docker.sock
        - --docker.domain=elaisa.org
        - --docker.watch=true
        - --docker.exposedbydefault=false
        - --acme.email=teusz.alexander@gmail.com
        - --acme.storage=acme.json
        - --acme.entryPoint=https
        - --acme.onHostRule=true
        - --acme.httpchallenge.entrypoint=http
      ports:
        - '80:80'
        - '443:443'
        - '18080:8080'
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        # use traefik file for ssl | soure: https://docs.traefik.io/user-guide/docker-and-lets-encrypt/
        - /opt/traefik/acme.json:/acme.json
      deploy:
        restart_policy:
          condition: any
        mode: global
        placement:
          constraints:
            - node.role == manager
        labels:
          # we don't want traefik to be available trough itself from the outsite world
          traefik.enable: 'false'
      networks:
        - frontend

# before starting the stack, this network has to be installed: 
# - docker network create --attachable --driver overlay frontend
# - docker network create --driver overlay --attachable --opt encrypted=true database
# the services network
networks: 
  frontend:
    external: true
  database:
    external: true
  monitoring: 
    external: true

# before starting the stack (one time), execute this command to create
# a docker volume for our mongodb data. The data witin this volume will
# persist on the host and will survive restarts of containers
# - docker volume create mongodb
volumes:
  mongodb:
    external: true
  # stores time-series db for metrics
  prometheus:
    external: true
  # stores configuration, users, data-sources for grafana
  grafana:
    external: true

# Docker secrets for hosting passwords, usernames etc.
secrets:
  mongodb_root_username:
    external: true
  mongodb_root_password:
    external: true